language: cpp
sudo: false

notifications:
  irc: "chat.freenode.net#formiga"

compiler:
  - gcc

env:
  matrix:
    - COMPILER=clang++-5 CCOMPILER=clang-5

env:
  #matrix:
  - OS_TYPE=centos OS_VERSION=6 ANSIBLE_VERSION=1.9.2

branches:
  only:
  - master

install:
  - ./handle_deps.sh

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - mkdir build

script:
  - cmake --build ./build --target all -- -j 2

after_success:

