language: cpp
sudo: false
notifications:
  email:
    recipients:
      - luisnuxx@outlook.com
    on_success: change
    on_failure: always
  irc: "chat.freenode.net#formiga"

#env:
#  - OS_TYPE=centos OS_VERSION=7

branches:
  only:
  - master

################
# build matrix #
################

matrix:
  include:

  # GCC
  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-5.4
      - CMAKE_OPTIONS=
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5.4', 'valgrind', 'ninja-build']

  # CLANG
  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-5.0
      - CMAKE_OPTIONS=
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
        packages: ['g++-6', 'clang-5.0']

before_script:
  #BOOST
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev
  - ./handle_deps.sh
  - uname -a
  - $CXX --version
script:
  # show OS/compiler version
  - mkdir -p build && cd build
  - cmake .. ${CMAKE_OPTIONS}
  - ls -l
  - pwd
  - cmake --build . --config Release
  - cd ..



