language: cpp
sudo: false

notifications:
  irc: "chat.freenode.net#formiga"

#env:
#  - OS_TYPE=centos OS_VERSION=7 ANSIBLE_VERSION=1.9.2

branches:
  only:
  - master

################
# build matrix #
################

matrix:
  include:

  # GCC
  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-4.9
      - CMAKE_OPTIONS=
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9', 'valgrind', 'ninja-build']

  # CLANG
  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-5.0
      - CMAKE_OPTIONS=
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
        packages: ['g++-6', 'clang-5.0']

before_script:
  - mkdir build

script:
  # show OS/compiler version
  - ./handle_deps.sh
  - uname -a
  - $CXX --version
  - cmake .
  - ls -l
  - pwd
  - cmake --build ./build --target all -- -j 2


